# Generated by Django 5.1.6 on 2025-03-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("contenido", models.TextField()),
                ("imagen_url", models.URLField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("romantico", "Romántico"),
                            ("tragico", "Trágico"),
                            ("drama", "Drama"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
